### ISSUE TITLE
Is global $shutdown_flag really needed?

### ISSUE THREAD

**Issue by mrclay** [jumbojett/vroom#3]
If you're handling the shutdown event, you know the system is shutting down. Devs should just pass this info along to any sub-processes they call.

```php
$var1 = "hello";
$var2 = "world";

elgg_register_event_handler('shutdown', 'system', function () use ($var1,$var2) {
    my_slow_notifications($var1, $var2, true);
});

function my_slow_notifications($var1, $var2, $shutting_down = false) {}
```

**Comment by jumbojett** [comment]
@mrclay how would we notify `my_slow_notifications` if the state change of `$shutting_down` changes to `true`?

**Comment by mrclay** [comment]
What do you mean by notify? While the function is executing the state of global events can't change. If it's called outside the shutdown handler, don't set the 3rd arg to true, in the handler *do* set it to true.

**Comment by jumbojett** [comment]
I misunderstood. Yes, what you proposed makes sense. 

Pros:
- It eliminates the use of a global which more programmatically proper. 

Cons:
- The developer is required to "hand hold" the code.

**Comment by jumbojett** [comment]
@mrclay I'm going to close this issue. If you have more insight or feedback, please re-open and we discuss this further. Thanks!
